### ISSUE TITLE
在X3上跑yolov8m-seg模型，推理时间600ms左右正常吗？且log输出如下error是什么原因，怎么解决呢？

### ISSUE THREAD

**Issue by CachCheng** [HorizonRDK/hobot_dnn#19]
运行时log输出信息如下：

[C][1001727][12-26][17:39:48:009][configuration.cpp:51][EasyDNN]EasyDNN version: 0.3.5
[BPU_PLAT]BPU Platform Version(1.3.1)!
[HBRT] set log level as 0. version = 3.13.27
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
ioctl write error, ret = -1 error = 121
keros_i2c_write failed
ioctl write error, ret = -1 error = 121
keros_i2c_write failed
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
ioctl read error, ret = -1 error = 121
keros_i2c_read failed
[000:000] (keros_util.cpp:99): keros_authentication failed, ret = 0
[000:000] (configuration.cpp:147): Keros key init failed.
[DNN] Runtime version = 1.8.4_(3.13.27 HBRT)
[HorizonRT] The model builder version = 1.18.2
preprocess:  0.027321577072143555
infer:  0.6133880615234375
postprocess:  0.01937723159790039
time:  0.6959570169448852
bus 0.9212772250175476
person 0.8948745131492615
person 0.873417317867279
person 0.8533942103385925
person 0.6052259206771851
【INFO】: Offload model "yolov8m-seg" Successfully.

**Comment by zhukao** [comment]
此仓库是板端推理框架，具体模型推理性能相关问题，请在开发者社区论坛上提问，会有相关专业同学支持：https://developer.horizon.ai/forum
