### ISSUE TITLE
关于dnn/hb_dnn.h

### ISSUE THREAD

**Issue by yttttkskr** [HorizonRDK/hobot_dnn#25]
我试着在自己电脑上跑该代码，检查依赖项的时候报错找不到dnn_node_data.h中include <dnn/hb_dnn.h>，请问该包是在开发板上才有的吗，还是说我可以在github上下载 ?

**Comment by zhukao** [comment]
hb_dnn.h是BPU推理库的头文件，在RDK的系统中，需要在开发板上编译，或者使用提供的docker交叉编译。

**Comment by yttttkskr** [comment]
好的，谢谢您
